name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python3 -m pip install -r requirements.txt
          python3 run.py
      - name: Create Release
        id: create_release
        uses: ncipollo/create-release@v1
        with:
          tag_name: v${{ github.run_date | format: "%Y%m%d%H%M" }}
          release_name: Release ${{ github.run_date | format: "%Y%m%d%H%M" }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: build/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
